spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
    alicloud:
      access-key: LTAI5tBbgmECFxm6LsggRgCa
      secret-key: gFFTpcZgGWUF75yLEoXRjYBGXbCc8w
      oss:
        bucket: lizheng-gulimall
        endpoint: oss-cn-shanghai.aliyuncs.com

server:
  port: 30000