spring:
  cloud:
    nacos:
      discovery:
        server-addr: 139.196.224.147:8848
        username: nacos
        password: nacos
    alicloud:
      access-key: LTAI5tBbgmECFxm6LsggRgCa
      secret-key: gFFTpcZgGWUF75yLEoXRjYBGXbCc8w
      oss:
        bucket: lizheng-gulimall
        endpoint: oss-cn-shanghai.aliyuncs.com
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        sms-sign-id: 2e65b1bb3d054466b82f0c9d125465e2
        template-id: 908e94ccf08b4476ba6c876d13f084ad
  application:
    name: gulimall-third-party

server:
  port: 30000