spring:
  cloud:
    nacos:
      discovery:
        server-addr: 139.196.224.147:8848
        username: nacos
        password: nacos
  #    alicloud:
#      access-key: LTAI5tBbgmECFxm6LsggRgCa
#      secret-key: gFFTpcZgGWUF75yLEoXRjYBGXbCc8w
#      oss:
#        bucket: lizheng-gulimall
#        endpoint: oss-cn-shanghai.aliyuncs.com
  application:
    name: gulimall-third-party

server:
  port: 30000