spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.57.248:8848
    alicloud:
      access-key: LTAI5tBbgmECFxm6LsggRgCa
      secret-key: gFFTpcZgGWUF75yLEoXRjYBGXbCc8w
      oss:
        bucket: lizheng-gulimall
        endpoint: oss-cn-shanghai.aliyuncs.com
  application:
    name: gulimall-third-party

server:
  port: 30000